import type { PrefectureConfig } from '../../types/prefecture.types.js';

// Île-de-France prefectures - TIER 1 (30s check interval)
// These have the highest demand and need maximum scraping frequency

export const TIER1_PREFECTURES: PrefectureConfig[] = [
  {
    id: 'paris_75',
    name: 'Paris',
    department: '75',
    region: 'Île-de-France',
    tier: 1,
    bookingUrl: 'https://www.prefecturedepolice.interieur.gouv.fr/demarches/rendez-vous',
    checkInterval: 30,
    bookingSystem: 'custom',
    selectors: {
      availableSlot: '.slot-available, .creneau-disponible, .calendar-day.available, [data-available="true"]',
      noSlotIndicator: '.no-availability, .aucun-creneau, .alert-warning',
      slotDate: '.slot-date, .date-creneau',
      slotTime: '.slot-time, .heure-creneau',
      cookieAccept: '#cookie-accept, .tarteaucitronAllow, .cookie-accept-btn',
      captchaDetect: 'iframe[src*="recaptcha"], iframe[src*="hcaptcha"], .g-recaptcha',
    },
    procedures: ['TITRE_SEJOUR', 'NATURALISATION'],
  },
  {
    id: 'bobigny_93',
    name: 'Bobigny',
    department: '93',
    region: 'Île-de-France',
    tier: 1,
    bookingUrl: 'https://www.seine-saint-denis.gouv.fr/booking/create',
    checkInterval: 30,
    bookingSystem: 'ants',
    selectors: {
      availableSlot: '.slot-available, .creneau-disponible, .day.available',
      noSlotIndicator: '.alert-warning, .no-slot-message',
      slotDate: '.slot-date',
      slotTime: '.slot-time',
      cookieAccept: '#cookie-consent-accept, .tarteaucitronAllow',
      procedureDropdown: 'select#procedure, select[name="procedure"]',
      nextButton: '.btn-primary, button[type="submit"]',
      captchaDetect: 'iframe[src*="recaptcha"]',
    },
    procedures: ['TITRE_SEJOUR', 'NATURALISATION', 'VISA'],
  },
  {
    id: 'creteil_94',
    name: 'Créteil',
    department: '94',
    region: 'Île-de-France',
    tier: 1,
    bookingUrl: 'https://www.val-de-marne.gouv.fr/booking/create',
    checkInterval: 30,
    bookingSystem: 'ants',
    selectors: {
      availableSlot: '.slot-available, .creneau-disponible',
      noSlotIndicator: '.alert-warning, .no-slot-message',
      slotDate: '.slot-date',
      slotTime: '.slot-time',
      cookieAccept: '#cookie-consent-accept',
      captchaDetect: 'iframe[src*="recaptcha"]',
    },
    procedures: ['TITRE_SEJOUR', 'NATURALISATION'],
  },
  {
    id: 'nanterre_92',
    name: 'Nanterre',
    department: '92',
    region: 'Île-de-France',
    tier: 1,
    bookingUrl: 'https://www.hauts-de-seine.gouv.fr/booking/create',
    checkInterval: 30,
    bookingSystem: 'ants',
    selectors: {
      availableSlot: '.slot-available, .creneau-disponible',
      noSlotIndicator: '.alert-warning, .no-slot-message',
      slotDate: '.slot-date',
      slotTime: '.slot-time',
      cookieAccept: '#cookie-consent-accept',
      captchaDetect: 'iframe[src*="recaptcha"]',
    },
    procedures: ['TITRE_SEJOUR', 'NATURALISATION'],
  },
  {
    id: 'evry_91',
    name: 'Évry',
    department: '91',
    region: 'Île-de-France',
    tier: 1,
    bookingUrl: 'https://www.essonne.gouv.fr/booking/create',
    checkInterval: 30,
    bookingSystem: 'ants',
    selectors: {
      availableSlot: '.slot-available, .creneau-disponible',
      noSlotIndicator: '.alert-warning, .no-slot-message',
      slotDate: '.slot-date',
      slotTime: '.slot-time',
      cookieAccept: '#cookie-consent-accept',
      captchaDetect: 'iframe[src*="recaptcha"]',
    },
    procedures: ['TITRE_SEJOUR', 'NATURALISATION'],
  },
  {
    id: 'cergy_95',
    name: 'Cergy-Pontoise',
    department: '95',
    region: 'Île-de-France',
    tier: 1,
    bookingUrl: 'https://www.val-d-oise.gouv.fr/booking/create',
    checkInterval: 30,
    bookingSystem: 'ants',
    selectors: {
      availableSlot: '.slot-available, .creneau-disponible',
      noSlotIndicator: '.alert-warning, .no-slot-message',
      slotDate: '.slot-date',
      slotTime: '.slot-time',
      cookieAccept: '#cookie-consent-accept',
      captchaDetect: 'iframe[src*="recaptcha"]',
    },
    procedures: ['TITRE_SEJOUR', 'NATURALISATION'],
  },
  {
    id: 'melun_77',
    name: 'Melun',
    department: '77',
    region: 'Île-de-France',
    tier: 1,
    bookingUrl: 'https://www.seine-et-marne.gouv.fr/booking/create',
    checkInterval: 30,
    bookingSystem: 'ants',
    selectors: {
      availableSlot: '.slot-available, .creneau-disponible',
      noSlotIndicator: '.alert-warning, .no-slot-message',
      slotDate: '.slot-date',
      slotTime: '.slot-time',
      cookieAccept: '#cookie-consent-accept',
      captchaDetect: 'iframe[src*="recaptcha"]',
    },
    procedures: ['TITRE_SEJOUR', 'NATURALISATION'],
  },
  {
    id: 'versailles_78',
    name: 'Versailles',
    department: '78',
    region: 'Île-de-France',
    tier: 1,
    bookingUrl: 'https://www.yvelines.gouv.fr/booking/create',
    checkInterval: 30,
    bookingSystem: 'ants',
    selectors: {
      availableSlot: '.slot-available, .creneau-disponible',
      noSlotIndicator: '.alert-warning, .no-slot-message',
      slotDate: '.slot-date',
      slotTime: '.slot-time',
      cookieAccept: '#cookie-consent-accept',
      captchaDetect: 'iframe[src*="recaptcha"]',
    },
    procedures: ['TITRE_SEJOUR', 'NATURALISATION'],
  },
];

export default TIER1_PREFECTURES;
