import type { PrefectureConfig } from '../../types/prefecture.types.js';

// Standard ANTS selectors used by most prefectures
const ANTS_SELECTORS = {
  availableSlot: '.slot-available, .creneau-disponible, .calendar-day.available',
  noSlotIndicator: '.alert-warning, .no-slot-message, .aucun-creneau-disponible',
  slotDate: '.slot-date, .date-creneau',
  slotTime: '.slot-time, .heure-creneau',
  cookieAccept: '#cookie-consent-accept, .tarteaucitronAllow',
  captchaDetect: 'iframe[src*="recaptcha"]',
};

// Helper to create ANTS prefecture config
function createAntsPrefecture(
  id: string,
  name: string,
  department: string,
  region: string,
  urlSlug: string
): PrefectureConfig {
  return {
    id,
    name,
    department,
    region,
    tier: 3,
    bookingUrl: `https://www.${urlSlug}.gouv.fr/booking/create`,
    checkInterval: 120,
    bookingSystem: 'ants',
    selectors: ANTS_SELECTORS,
    procedures: ['TITRE_SEJOUR', 'NATURALISATION'],
  };
}

// TIER 3 prefectures (120s check interval) - All remaining metropolitan + overseas
export const TIER3_PREFECTURES: PrefectureConfig[] = [
  // Metropolitan France
  createAntsPrefecture('bourg_01', 'Bourg-en-Bresse', '01', 'Auvergne-Rhône-Alpes', 'ain'),
  createAntsPrefecture('laon_02', 'Laon', '02', 'Hauts-de-France', 'aisne'),
  createAntsPrefecture('moulins_03', 'Moulins', '03', 'Auvergne-Rhône-Alpes', 'allier'),
  createAntsPrefecture('digne_04', 'Digne-les-Bains', '04', 'Provence-Alpes-Côte d\'Azur', 'alpes-de-haute-provence'),
  createAntsPrefecture('gap_05', 'Gap', '05', 'Provence-Alpes-Côte d\'Azur', 'hautes-alpes'),
  createAntsPrefecture('privas_07', 'Privas', '07', 'Auvergne-Rhône-Alpes', 'ardeche'),
  createAntsPrefecture('charleville_08', 'Charleville-Mézières', '08', 'Grand Est', 'ardennes'),
  createAntsPrefecture('foix_09', 'Foix', '09', 'Occitanie', 'ariege'),
  createAntsPrefecture('troyes_10', 'Troyes', '10', 'Grand Est', 'aube'),
  createAntsPrefecture('carcassonne_11', 'Carcassonne', '11', 'Occitanie', 'aude'),
  createAntsPrefecture('rodez_12', 'Rodez', '12', 'Occitanie', 'aveyron'),
  createAntsPrefecture('caen_14', 'Caen', '14', 'Normandie', 'calvados'),
  createAntsPrefecture('aurillac_15', 'Aurillac', '15', 'Auvergne-Rhône-Alpes', 'cantal'),
  createAntsPrefecture('angouleme_16', 'Angoulême', '16', 'Nouvelle-Aquitaine', 'charente'),
  createAntsPrefecture('larochelle_17', 'La Rochelle', '17', 'Nouvelle-Aquitaine', 'charente-maritime'),
  createAntsPrefecture('bourges_18', 'Bourges', '18', 'Centre-Val de Loire', 'cher'),
  createAntsPrefecture('tulle_19', 'Tulle', '19', 'Nouvelle-Aquitaine', 'correze'),
  createAntsPrefecture('ajaccio_2a', 'Ajaccio', '2A', 'Corse', 'corse-du-sud'),
  createAntsPrefecture('bastia_2b', 'Bastia', '2B', 'Corse', 'haute-corse'),
  createAntsPrefecture('dijon_21', 'Dijon', '21', 'Bourgogne-Franche-Comté', 'cote-dor'),
  createAntsPrefecture('stbrieuc_22', 'Saint-Brieuc', '22', 'Bretagne', 'cotes-darmor'),
  createAntsPrefecture('gueret_23', 'Guéret', '23', 'Nouvelle-Aquitaine', 'creuse'),
  createAntsPrefecture('perigueux_24', 'Périgueux', '24', 'Nouvelle-Aquitaine', 'dordogne'),
  createAntsPrefecture('besancon_25', 'Besançon', '25', 'Bourgogne-Franche-Comté', 'doubs'),
  createAntsPrefecture('valence_26', 'Valence', '26', 'Auvergne-Rhône-Alpes', 'drome'),
  createAntsPrefecture('evreux_27', 'Évreux', '27', 'Normandie', 'eure'),
  createAntsPrefecture('chartres_28', 'Chartres', '28', 'Centre-Val de Loire', 'eure-et-loir'),
  createAntsPrefecture('quimper_29', 'Quimper', '29', 'Bretagne', 'finistere'),
  createAntsPrefecture('nimes_30', 'Nîmes', '30', 'Occitanie', 'gard'),
  createAntsPrefecture('auch_32', 'Auch', '32', 'Occitanie', 'gers'),
  createAntsPrefecture('chateauroux_36', 'Châteauroux', '36', 'Centre-Val de Loire', 'indre'),
  createAntsPrefecture('tours_37', 'Tours', '37', 'Centre-Val de Loire', 'indre-et-loire'),
  createAntsPrefecture('lons_39', 'Lons-le-Saunier', '39', 'Bourgogne-Franche-Comté', 'jura'),
  createAntsPrefecture('mont_40', 'Mont-de-Marsan', '40', 'Nouvelle-Aquitaine', 'landes'),
  createAntsPrefecture('blois_41', 'Blois', '41', 'Centre-Val de Loire', 'loir-et-cher'),
  createAntsPrefecture('stetienne_42', 'Saint-Étienne', '42', 'Auvergne-Rhône-Alpes', 'loire'),
  createAntsPrefecture('lepuy_43', 'Le Puy-en-Velay', '43', 'Auvergne-Rhône-Alpes', 'haute-loire'),
  createAntsPrefecture('orleans_45', 'Orléans', '45', 'Centre-Val de Loire', 'loiret'),
  createAntsPrefecture('cahors_46', 'Cahors', '46', 'Occitanie', 'lot'),
  createAntsPrefecture('agen_47', 'Agen', '47', 'Nouvelle-Aquitaine', 'lot-et-garonne'),
  createAntsPrefecture('mende_48', 'Mende', '48', 'Occitanie', 'lozere'),
  createAntsPrefecture('angers_49', 'Angers', '49', 'Pays de la Loire', 'maine-et-loire'),
  createAntsPrefecture('stlo_50', 'Saint-Lô', '50', 'Normandie', 'manche'),
  createAntsPrefecture('chalons_51', 'Châlons-en-Champagne', '51', 'Grand Est', 'marne'),
  createAntsPrefecture('chaumont_52', 'Chaumont', '52', 'Grand Est', 'haute-marne'),
  createAntsPrefecture('laval_53', 'Laval', '53', 'Pays de la Loire', 'mayenne'),
  createAntsPrefecture('nancy_54', 'Nancy', '54', 'Grand Est', 'meurthe-et-moselle'),
  createAntsPrefecture('barleduc_55', 'Bar-le-Duc', '55', 'Grand Est', 'meuse'),
  createAntsPrefecture('vannes_56', 'Vannes', '56', 'Bretagne', 'morbihan'),
  createAntsPrefecture('metz_57', 'Metz', '57', 'Grand Est', 'moselle'),
  createAntsPrefecture('nevers_58', 'Nevers', '58', 'Bourgogne-Franche-Comté', 'nievre'),
  createAntsPrefecture('beauvais_60', 'Beauvais', '60', 'Hauts-de-France', 'oise'),
  createAntsPrefecture('alencon_61', 'Alençon', '61', 'Normandie', 'orne'),
  createAntsPrefecture('arras_62', 'Arras', '62', 'Hauts-de-France', 'pas-de-calais'),
  createAntsPrefecture('clermont_63', 'Clermont-Ferrand', '63', 'Auvergne-Rhône-Alpes', 'puy-de-dome'),
  createAntsPrefecture('pau_64', 'Pau', '64', 'Nouvelle-Aquitaine', 'pyrenees-atlantiques'),
  createAntsPrefecture('tarbes_65', 'Tarbes', '65', 'Occitanie', 'hautes-pyrenees'),
  createAntsPrefecture('perpignan_66', 'Perpignan', '66', 'Occitanie', 'pyrenees-orientales'),
  createAntsPrefecture('colmar_68', 'Colmar', '68', 'Grand Est', 'haut-rhin'),
  createAntsPrefecture('vesoul_70', 'Vesoul', '70', 'Bourgogne-Franche-Comté', 'haute-saone'),
  createAntsPrefecture('macon_71', 'Mâcon', '71', 'Bourgogne-Franche-Comté', 'saone-et-loire'),
  createAntsPrefecture('lemans_72', 'Le Mans', '72', 'Pays de la Loire', 'sarthe'),
  createAntsPrefecture('chambery_73', 'Chambéry', '73', 'Auvergne-Rhône-Alpes', 'savoie'),
  createAntsPrefecture('annecy_74', 'Annecy', '74', 'Auvergne-Rhône-Alpes', 'haute-savoie'),
  createAntsPrefecture('niort_79', 'Niort', '79', 'Nouvelle-Aquitaine', 'deux-sevres'),
  createAntsPrefecture('amiens_80', 'Amiens', '80', 'Hauts-de-France', 'somme'),
  createAntsPrefecture('albi_81', 'Albi', '81', 'Occitanie', 'tarn'),
  createAntsPrefecture('montauban_82', 'Montauban', '82', 'Occitanie', 'tarn-et-garonne'),
  createAntsPrefecture('toulon_83', 'Toulon', '83', 'Provence-Alpes-Côte d\'Azur', 'var'),
  createAntsPrefecture('avignon_84', 'Avignon', '84', 'Provence-Alpes-Côte d\'Azur', 'vaucluse'),
  createAntsPrefecture('laroche_85', 'La Roche-sur-Yon', '85', 'Pays de la Loire', 'vendee'),
  createAntsPrefecture('poitiers_86', 'Poitiers', '86', 'Nouvelle-Aquitaine', 'vienne'),
  createAntsPrefecture('limoges_87', 'Limoges', '87', 'Nouvelle-Aquitaine', 'haute-vienne'),
  createAntsPrefecture('epinal_88', 'Épinal', '88', 'Grand Est', 'vosges'),
  createAntsPrefecture('auxerre_89', 'Auxerre', '89', 'Bourgogne-Franche-Comté', 'yonne'),
  createAntsPrefecture('belfort_90', 'Belfort', '90', 'Bourgogne-Franche-Comté', 'territoire-de-belfort'),
  
  // Overseas territories
  createAntsPrefecture('basseterre_971', 'Basse-Terre', '971', 'Guadeloupe', 'guadeloupe'),
  createAntsPrefecture('fortdefrance_972', 'Fort-de-France', '972', 'Martinique', 'martinique'),
  createAntsPrefecture('cayenne_973', 'Cayenne', '973', 'Guyane', 'guyane'),
  createAntsPrefecture('stdenis_974', 'Saint-Denis', '974', 'La Réunion', 'reunion'),
  createAntsPrefecture('mamoudzou_976', 'Mamoudzou', '976', 'Mayotte', 'mayotte'),
];

export default TIER3_PREFECTURES;
