import type { PrefectureConfig } from '../../types/prefecture.types.js';

// Major cities prefectures - TIER 2 (60s check interval)

export const TIER2_PREFECTURES: PrefectureConfig[] = [
  {
    id: 'lyon_69',
    name: 'Lyon',
    department: '69',
    region: 'Auvergne-Rhône-Alpes',
    tier: 2,
    bookingUrl: 'https://www.rhone.gouv.fr/booking/create',
    checkInterval: 60,
    bookingSystem: 'ants',
    selectors: {
      availableSlot: '.slot-available, .creneau-disponible',
      noSlotIndicator: '.alert-warning, .no-slot-message',
      slotDate: '.slot-date',
      cookieAccept: '#cookie-consent-accept',
      captchaDetect: 'iframe[src*="recaptcha"]',
    },
    procedures: ['TITRE_SEJOUR', 'NATURALISATION'],
  },
  {
    id: 'marseille_13',
    name: 'Marseille',
    department: '13',
    region: 'Provence-Alpes-Côte d\'Azur',
    tier: 2,
    bookingUrl: 'https://www.bouches-du-rhone.gouv.fr/booking/create',
    checkInterval: 60,
    bookingSystem: 'ants',
    selectors: {
      availableSlot: '.slot-available, .creneau-disponible',
      noSlotIndicator: '.alert-warning, .no-slot-message',
      slotDate: '.slot-date',
      cookieAccept: '#cookie-consent-accept',
      captchaDetect: 'iframe[src*="recaptcha"]',
    },
    procedures: ['TITRE_SEJOUR', 'NATURALISATION'],
  },
  {
    id: 'toulouse_31',
    name: 'Toulouse',
    department: '31',
    region: 'Occitanie',
    tier: 2,
    bookingUrl: 'https://www.haute-garonne.gouv.fr/booking/create',
    checkInterval: 60,
    bookingSystem: 'ants',
    selectors: {
      availableSlot: '.slot-available, .creneau-disponible',
      noSlotIndicator: '.alert-warning, .no-slot-message',
      slotDate: '.slot-date',
      cookieAccept: '#cookie-consent-accept',
      captchaDetect: 'iframe[src*="recaptcha"]',
    },
    procedures: ['TITRE_SEJOUR', 'NATURALISATION'],
  },
  {
    id: 'lille_59',
    name: 'Lille',
    department: '59',
    region: 'Hauts-de-France',
    tier: 2,
    bookingUrl: 'https://www.nord.gouv.fr/booking/create',
    checkInterval: 60,
    bookingSystem: 'ants',
    selectors: {
      availableSlot: '.slot-available, .creneau-disponible',
      noSlotIndicator: '.alert-warning, .no-slot-message',
      slotDate: '.slot-date',
      cookieAccept: '#cookie-consent-accept',
      captchaDetect: 'iframe[src*="recaptcha"]',
    },
    procedures: ['TITRE_SEJOUR', 'NATURALISATION'],
  },
  {
    id: 'nantes_44',
    name: 'Nantes',
    department: '44',
    region: 'Pays de la Loire',
    tier: 2,
    bookingUrl: 'https://www.loire-atlantique.gouv.fr/booking/create',
    checkInterval: 60,
    bookingSystem: 'ants',
    selectors: {
      availableSlot: '.slot-available, .creneau-disponible',
      noSlotIndicator: '.alert-warning, .no-slot-message',
      slotDate: '.slot-date',
      cookieAccept: '#cookie-consent-accept',
      captchaDetect: 'iframe[src*="recaptcha"]',
    },
    procedures: ['TITRE_SEJOUR', 'NATURALISATION'],
  },
  {
    id: 'bordeaux_33',
    name: 'Bordeaux',
    department: '33',
    region: 'Nouvelle-Aquitaine',
    tier: 2,
    bookingUrl: 'https://www.gironde.gouv.fr/booking/create',
    checkInterval: 60,
    bookingSystem: 'ants',
    selectors: {
      availableSlot: '.slot-available, .creneau-disponible',
      noSlotIndicator: '.alert-warning, .no-slot-message',
      slotDate: '.slot-date',
      cookieAccept: '#cookie-consent-accept',
      captchaDetect: 'iframe[src*="recaptcha"]',
    },
    procedures: ['TITRE_SEJOUR', 'NATURALISATION'],
  },
  {
    id: 'montpellier_34',
    name: 'Montpellier',
    department: '34',
    region: 'Occitanie',
    tier: 2,
    bookingUrl: 'https://www.herault.gouv.fr/booking/create',
    checkInterval: 60,
    bookingSystem: 'ants',
    selectors: {
      availableSlot: '.slot-available, .creneau-disponible',
      noSlotIndicator: '.alert-warning, .no-slot-message',
      slotDate: '.slot-date',
      cookieAccept: '#cookie-consent-accept',
      captchaDetect: 'iframe[src*="recaptcha"]',
    },
    procedures: ['TITRE_SEJOUR', 'NATURALISATION'],
  },
  {
    id: 'strasbourg_67',
    name: 'Strasbourg',
    department: '67',
    region: 'Grand Est',
    tier: 2,
    bookingUrl: 'https://www.bas-rhin.gouv.fr/booking/create',
    checkInterval: 60,
    bookingSystem: 'ants',
    selectors: {
      availableSlot: '.slot-available, .creneau-disponible',
      noSlotIndicator: '.alert-warning, .no-slot-message',
      slotDate: '.slot-date',
      cookieAccept: '#cookie-consent-accept',
      captchaDetect: 'iframe[src*="recaptcha"]',
    },
    procedures: ['TITRE_SEJOUR', 'NATURALISATION'],
  },
  {
    id: 'nice_06',
    name: 'Nice',
    department: '06',
    region: 'Provence-Alpes-Côte d\'Azur',
    tier: 2,
    bookingUrl: 'https://www.alpes-maritimes.gouv.fr/booking/create',
    checkInterval: 60,
    bookingSystem: 'ants',
    selectors: {
      availableSlot: '.slot-available, .creneau-disponible',
      noSlotIndicator: '.alert-warning, .no-slot-message',
      slotDate: '.slot-date',
      cookieAccept: '#cookie-consent-accept',
      captchaDetect: 'iframe[src*="recaptcha"]',
    },
    procedures: ['TITRE_SEJOUR', 'NATURALISATION'],
  },
  {
    id: 'rouen_76',
    name: 'Rouen',
    department: '76',
    region: 'Normandie',
    tier: 2,
    bookingUrl: 'https://www.seine-maritime.gouv.fr/booking/create',
    checkInterval: 60,
    bookingSystem: 'ants',
    selectors: {
      availableSlot: '.slot-available, .creneau-disponible',
      noSlotIndicator: '.alert-warning, .no-slot-message',
      slotDate: '.slot-date',
      cookieAccept: '#cookie-consent-accept',
      captchaDetect: 'iframe[src*="recaptcha"]',
    },
    procedures: ['TITRE_SEJOUR', 'NATURALISATION'],
  },
  {
    id: 'rennes_35',
    name: 'Rennes',
    department: '35',
    region: 'Bretagne',
    tier: 2,
    bookingUrl: 'https://www.ille-et-vilaine.gouv.fr/booking/create',
    checkInterval: 60,
    bookingSystem: 'ants',
    selectors: {
      availableSlot: '.slot-available, .creneau-disponible',
      noSlotIndicator: '.alert-warning, .no-slot-message',
      slotDate: '.slot-date',
      cookieAccept: '#cookie-consent-accept',
      captchaDetect: 'iframe[src*="recaptcha"]',
    },
    procedures: ['TITRE_SEJOUR', 'NATURALISATION'],
  },
  {
    id: 'grenoble_38',
    name: 'Grenoble',
    department: '38',
    region: 'Auvergne-Rhône-Alpes',
    tier: 2,
    bookingUrl: 'https://www.isere.gouv.fr/booking/create',
    checkInterval: 60,
    bookingSystem: 'ants',
    selectors: {
      availableSlot: '.slot-available, .creneau-disponible',
      noSlotIndicator: '.alert-warning, .no-slot-message',
      slotDate: '.slot-date',
      cookieAccept: '#cookie-consent-accept',
      captchaDetect: 'iframe[src*="recaptcha"]',
    },
    procedures: ['TITRE_SEJOUR', 'NATURALISATION'],
  },
];

export default TIER2_PREFECTURES;
